url: "http://silbongio.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Silvina Bongiovanni" # the name of your site, e.g. ACME Corp.
description: "Associate Professor, Dept. Romance and Classical Studies, Michigan State University"
